name: LaTeX
on: [push, pull_request]
jobs:
  latexmk:
    if: "! contains(github.event.head_commit.message, '[ci skip]')"    

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@master
        with:
          root_file: RJwrapper.tex
          
      - name: Check PDF files
        run: |
          file RJwrapper.pdf | grep -q ' PDF '

      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: article_pdf
          path: RJwrapper.pdf
        if: always()
        