name: Compile LaTeX to PDF
on: [push, pull_request]
jobs:
  latex:
    if: "! contains(github.event.head_commit.message, '[ci skip]')"    

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@master
        with:
          root_file: RJwrapper.tex
          working_directory: output/
          
      - name: Check PDF files
        run: |
          file test/RJwrapper.pdf | grep -q ' PDF '

      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: output
          path: output
        if: always()
        