name: Spelling
on: [push, pull_request]
jobs:
  aspell:
    if: "! contains(github.event.head_commit.message, '[ci skip]')"    

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        
      - name: Spell check LaTeX document
        uses: mh61503891/action-paper-aspell@master
        env:
            ASPELL_LANG: en
            ASPELL_MODE: tex
            ASPELL_PERSONAL: ./.aspell.en.pws
            ASPELL_FILES: bengtsson.tex
